### ISSUE TITLE
datetimepicker

### ISSUE THREAD

**Issue by Murillhou** [alanst32/MeanCrudProject#1]
Hi, I cloned the repository and downloaded jquery, datatables, angular and bootstrap plus I placed them on the right folders. 
Still, jquery doesn´t recognice .datetimepicker ¿maybe I am missing something? jquery is last version.
Thank you.

**Comment by alanst32** [comment]
Hello @Murillhou, honestly without looking your code I cannot say what the reason is. What javascript error  you are getting?

**Comment by Murillhou** [comment]
Hi, thank you for replying. Google chrome console throw the following warning and error:jquery-3.1.1.js:3846 jQuery.Deferred exception: $(...).datetimepicker is not a function TypeError: $(...).datetimepicker is not a function
    at HTMLDocument.<anonymous> (http://localhost:3000/angularApp.js:117:25)
    at mightThrow (http://localhost:3000/resources/jquery-3.1.1.js:3570:29)
    at process (http://localhost:3000/resources/jquery-3.1.1.js:3638:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.1.1.js:3846
process @ jquery-3.1.1.js:3642
jquery-3.1.1.js:3855 Uncaught TypeError: $(...).datetimepicker is not a function
    at HTMLDocument.<anonymous> (angularApp.js:117)
    at mightThrow (jquery-3.1.1.js:3570)
    at process (jquery-3.1.1.js:3638)

**Comment by Murillhou** [comment]
I would say that the code is exactly the same as the one pn github, but please let me check it. Thank you very much.
